### ISSUE TITLE
Determine encoding conflict between Arduino and IOx Application

### ISSUE THREAD

**Issue by hpreston** [imapex/ioxduino#2]
Currently when trying to read incoming data from the Arduino within the IOx application the data isn't decoded properly.  

Data currently looks like this: 

```
Incoming Data found.
['Sun Sep 11 14:26:22 2016', 'T\xba\x1a']
```

**Comment by hpreston** [comment]
Also generates this error when trying to access the information json.dumps in the API code.  

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
  File "/appdir/app/main.py", line 87, in simple_app
    ret = json.dumps(alerts)
  File "/usr/lib/python2.7/json/__init__.py", line 231, in dumps
  File "/usr/lib/python2.7/json/encoder.py", line 201, in encode
  File "/usr/lib/python2.7/json/encoder.py", line 264, in iterencode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xba in position 1: invalid start byte
```

**Comment by hpreston** [comment]
Wasn't encoding, but was rather a difference between TTL and RS232 communications.  Arduino build was updated to reflect the need to convert.
